package com.hardware.compatibility.config;

import io.jsonwebtoken.*;
import io.jsonwebtoken.security.Keys;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import javax.crypto.SecretKey;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

/**
 * JWT工具类
 */
@Component
@Slf4j
public class JwtUtil {
    
    @Value("${app.jwt.secret}")
    private String jwtSecret;
    
    @Value("${app.jwt.expiration:86400000}") // 默认24小时
    private long jwtExpirationMs;
    
    @Value("${app.jwt.refresh-expiration:604800000}") // 默认7天
    private long refreshExpirationMs;
    
    private static final Path KEY_FILE = Paths.get(System.getProperty("user.dir"), "data", ".jwt-key");
    
    /**
     * 初始化JWT密钥 — 首次运行时自动生成，后续复用
     */
    @PostConstruct
    public void initJwtSecret() {
        if (jwtSecret != null && !jwtSecret.isBlank() && !jwtSecret.equals("your-secret-key-here")) {
            log.info("JWT密钥已配置，使用自定义密钥");
            return;
        }
        try {
            if (Files.exists(KEY_FILE)) {
                jwtSecret = Files.readString(KEY_FILE).trim();
                log.info("JWT密钥已从持久化文件加载: {}", KEY_FILE);
            } else {
                Files.createDirectories(KEY_FILE.getParent());
                byte[] keyBytes = new byte[64];
                new SecureRandom().nextBytes(keyBytes);
                jwtSecret = Base64.getEncoder().encodeToString(keyBytes);
                Files.writeString(KEY_FILE, jwtSecret);
                log.info("JWT密钥已自动生成并保存到: {}", KEY_FILE);
            }
        } catch (Exception e) {
            log.warn("无法持久化JWT密钥，使用临时密钥: {}", e.getMessage());
            jwtSecret = "AutoGenerated-" + Base64.getEncoder().encodeToString(
                String.valueOf(System.currentTimeMillis()).getBytes());
        }
    }
    
    /**
     * 生成访问令牌
     */
    public String generateAccessToken(UserDetails userDetails) {
        Map<String, Object> claims = new HashMap<>();
        return createToken(claims, userDetails.getUsername(), jwtExpirationMs);
    }
    
    /**
     * 生成访问令牌（基于用户名）
     */
    public String generateAccessToken(String username) {
        Map<String, Object> claims = new HashMap<>();
        return createToken(claims, username, jwtExpirationMs);
    }
    
    /**
     * 生成刷新令牌
     */
    public String generateRefreshToken(UserDetails userDetails) {
        Map<String, Object> claims = new HashMap<>();
        return createToken(claims, userDetails.getUsername(), refreshExpirationMs);
    }
    
    /**
     * 生成刷新令牌（基于用户名）
     */
    public String generateRefreshToken(String username) {
        Map<String, Object> claims = new HashMap<>();
        return createToken(claims, username, refreshExpirationMs);
    }
    
    /**
     * 创建令牌
     */
    private String createToken(Map<String, Object> claims, String subject, long expiration) {
        return Jwts.builder()
                .setClaims(claims)
                .setSubject(subject)
                .setIssuedAt(new Date(System.currentTimeMillis()))
                .setExpiration(new Date(System.currentTimeMillis() + expiration))
                .signWith(getSigningKey(), SignatureAlgorithm.HS256)
                .compact();
    }
    
    /**
     * 验证令牌
     */
    public boolean validateToken(String token) {
        try {
            Jwts.parserBuilder()
                    .setSigningKey(getSigningKey())
                    .build()
                    .parseClaimsJws(token);
            return true;
        } catch (SecurityException e) {
            System.err.println("JWT签名验证失败: " + e.getMessage());
        } catch (MalformedJwtException e) {
            System.err.println("JWT令牌格式错误: " + e.getMessage());
        } catch (ExpiredJwtException e) {
            System.err.println("JWT令牌已过期: " + e.getMessage());
        } catch (UnsupportedJwtException e) {
            System.err.println("不支持的JWT令牌: " + e.getMessage());
        } catch (IllegalArgumentException e) {
            System.err.println("JWT令牌参数错误: " + e.getMessage());
        }
        return false;
    }
    
    /**
     * 从令牌中提取用户名
     */
    public String extractUsername(String token) {
        return extractClaim(token, Claims::getSubject);
    }
    
    /**
     * 从令牌中提取过期时间
     */
    public Date extractExpiration(String token) {
        return extractClaim(token, Claims::getExpiration);
    }
    
    /**
     * 提取声明
     */
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = extractAllClaims(token);
        return claimsResolver.apply(claims);
    }
    
    /**
     * 提取所有声明
     */
    private Claims extractAllClaims(String token) {
        return Jwts.parserBuilder()
                .setSigningKey(getSigningKey())
                .build()
                .parseClaimsJws(token)
                .getBody();
    }
    

    
    /**
     * 获取签名密钥
     */
    private SecretKey getSigningKey() {
        return Keys.hmacShaKeyFor(jwtSecret.getBytes());
    }
    
    /**
     * 获取访问令牌过期时间（秒）
     */
    public Long getAccessTokenExpiration() {
        return jwtExpirationMs / 1000;
    }
}